#!/bin/bash

set -eu

KIND_LOAD=${1:-false}
KIND_NODE=${2:-kind}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

REGISTRY_NAME=quay.io
REGISTRY_OWNER=halkyonio

IMAGE_NAME=skopeo-jq
IMAGE_TAG=0.1.3
IMAGE_FULL_NAME=$REGISTRY_NAME/$REGISTRY_OWNER/$IMAGE_NAME

podman manifest create $IMAGE_FULL_NAME:$IMAGE_TAG

podman build --platform linux/amd64,linux/arm64 --manifest $IMAGE_FULL_NAME:$IMAGE_TAG $SCRIPT_DIR/.

podman tag $IMAGE_FULL_NAME:$IMAGE_TAG $IMAGE_FULL_NAME:latest

podman push $IMAGE_FULL_NAME:$IMAGE_TAG $IMAGE_FULL_NAME:latest
podman manifest push $IMAGE_FULL_NAME:$IMAGE_TAG

if [[ $KIND_LOAD == "true" ]]; then
  kind load docker-image $IMAGE_FULL_NAME:$IMAGE_TAG -n $KIND_NODE
fi
