FROM ubuntu
RUN apt-get update && apt-get install curl sshpass -yq
RUN curl -LO https://www.dropbox.com/sh/lzq0qi2g7ep32eu/AAACAJIoJucg-n8Nl2B02Zxfa/orka-cli-linux && chmod +x orka-cli-linux && mv orka-cli-linux /usr/bin/orka
